name: 'Release'

on:
    workflow_dispatch:

jobs:
    publish:
        name: 'Publish'
        permissions:
            contents: write
        strategy:
            fail-fast: false
            matrix:
                include:
                - platform: 'macos-latest'
                  args: '--target universal-apple-darwin'
                - platform: 'ubuntu-22.04'
                  args: ''
                - platform: 'windows-latest'
                  args: ''

        runs-on: ${{ matrix.platform }}
        steps:
            - uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                node-version: 20

            - name: install Rust stable
              uses: actions-rs/toolchain@v1
              with:
                toolchain: stable

            - name: Install Platform Dependecies
              if: matrix.platform == 'ubuntu-22.04' # This must match the platform value defined above.
              run: |
                sudo apt-get update
                sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

            - name: Install NPM Dependencies
              run: yarn install

            - name: Build
              uses: tauri-apps/tauri-action@v0
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
                TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
              with:
                tagName: v__VERSION__
                releaseName: v__VERSION__
                releaseBody: 'Release v__VERSION__'
                releaseDraft: true
                prerelease: false
                args: ${{ matrix.args }}
            
            
