name: "Rust Checker and Coverage"
on:
    pull_request:
    push:
        branches:
            - main

jobs:
    lint-build:
        name: "Lint, Build and Test"
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pull-requests: write

        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                node-version: 20

            - name: "Install Dependencies"
              run: |
                sudo apt-get update
                sudo apt-get install libwebkit2gtk-4.0-dev \
                  build-essential \
                  curl \
                  wget \
                  file \
                  libssl-dev \
                  libgtk-3-dev \
                  libayatana-appindicator3-dev \
                  librsvg2-dev

                curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh -s -- -y

                npm install --global yarn
                yarn

            - name: "Lint"
              run: |
                cd src-tauri
                cargo clippy

            - name: "Build"
              run: yarn tauri build

            - name: Install cargo-llvm-cov
              uses: taiki-e/install-action@cargo-llvm-cov

            - name: Generate code coverage
              working-directory: src-tauri
              run: cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info

            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v3
              with:
                files: lcov.info
                fail_ci_if_error: false
              env:
                CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
