name: "Rust Checker and Coverage"
on:
    pull_request:
    push:
        branches:
            - main

jobs:
    changes:
        name: "Changes"
        runs-on: ubuntu-latest
        outputs:
            rust: ${{ steps.changes.outputs.rust }}
        steps:
            - uses: actions/checkout@v4
            - uses: dorny/paths-filter@v3
              with:
                filters: |
                    rust:
                        - 'src-tauri/**'  
    
    lint-build:
        name: "Lint And Build"
        runs-on: ubuntu-latest
        needs: changes

        if: ${{ needs.changes.outputs.rust == 'true' || github.ref_name == 'main' }}

        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4

            - name: "Install Dependencies"
              run: |
                npm install --global yarn
                yarn

            - name: "Lint"
              run: |
                cd src-tauri
                cargo clippy

            - name: "Build"
              run: yarn tauri build
    
    test:
        name: "Test"
        runs-on: ubuntu-latest
        needs: lint-build

        if: ${{ needs.changes.outputs.rust == 'true' || github.ref_name == 'main' }}

        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4

            - name: "Install Dependencies"
              run: |
                npm install --global yarn
                yarn
                npm run build

            - uses: actions-rs/toolchain@v1
              with:
                profile: minimal
                toolchain: nightly
                components: llvm-tools-preview

            - uses: Swatinem/fucov@v1

            - uses: codecov/codecov-action@v1
              with:
                directory: coverage
