name: "Rust Checker and Coverage"
on:
    pull_request:
    merge_group:
    push:
        branches:
            - main

jobs:
    lint:
        name: "Lint"
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pull-requests: write

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                node-version: 20

            - name: "Install Dependencies"
              run: |
                sudo apt-get update
                sudo apt-get install libwebkit2gtk-4.0-dev \
                  build-essential \
                  curl \
                  wget \
                  file \
                  libssl-dev \
                  libgtk-3-dev \
                  libayatana-appindicator3-dev \
                  librsvg2-dev

                curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh -s -- -y

                npm install --global yarn
                yarn
                yarn build

            - name: Configure sccache env var
              run: | 
                    echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV
                    echo "SCCACHE_GHA_ENABLED=true" >> $GITHUB_ENV
          
            - name: Run sccache-cache
              uses: mozilla-actions/sccache-action@v0.0.6

            - name: "Lint"
              run: |
                cd src-tauri
                cargo clippy --all-features --workspace -- -D warnings
  
    coverage:
        name: "Coverage"
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pull-requests: write

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                node-version: 20

            - name: "Install Dependencies"
              run: |
                sudo apt-get update
                sudo apt-get install libwebkit2gtk-4.0-dev \
                  build-essential \
                  curl \
                  wget \
                  file \
                  libssl-dev \
                  libgtk-3-dev \
                  libayatana-appindicator3-dev \
                  librsvg2-dev

                curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh -s -- -y

                npm install --global yarn
                yarn
                yarn build

            - name: Configure sccache env var
              run: | 
                    echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV
                    echo "SCCACHE_GHA_ENABLED=true" >> $GITHUB_ENV
          
            - name: Run sccache-cache
              uses: mozilla-actions/sccache-action@v0.0.6

            - name: Install cargo-llvm-cov
              uses: taiki-e/install-action@cargo-llvm-cov

            - name: Generate code coverage
              working-directory: src-tauri
              run: cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info

            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v4
              with:
                files: lcov.info
                fail_ci_if_error: false
              env:
                CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
