name: "Rust Checker and Coverage"
on:
    pull_request:
    merge_group:
    push:
        branches:
            - main

jobs:
    lint:
        name: "Lint"
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pull-requests: write

        steps:
            - uses: actions/checkout@v4

            - uses: dorny/paths-filter@v3
              id: changes
              with:
                filters: |
                  src:
                    - 'src-tauri/**'
                    - '.github/workflows/**'

            - uses: actions/setup-node@v4
              if: steps.changes.outputs.src == 'true'
              with:
                node-version: 22

            - name: "Install Dependencies"
              if: steps.changes.outputs.src == 'true'
              run: |
                sudo apt-get update
                sudo apt-get install libwebkit2gtk-4.1-dev \
                  build-essential \
                  curl \
                  wget \
                  file \
                  libssl-dev \
                  libgtk-3-dev \
                  libayatana-appindicator3-dev \
                  librsvg2-dev \
                  libsoup2.4-dev

                curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh -s -- -y

                npm install --global yarn
                yarn
                yarn build

            - name: "Lint"
              if: steps.changes.outputs.src == 'true'
              run: |
                cd src-tauri
                cargo clippy --all-features --workspace -- -D warnings
  
    coverage:
        name: "Coverage"
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pull-requests: write

        steps:
            - uses: actions/checkout@v4

            - uses: dorny/paths-filter@v3
              id: changes
              with:
                filters: |
                  src:
                    - 'src-tauri/**'
                    - '.github/workflows/**'

            - uses: actions/setup-node@v4
              if: steps.changes.outputs.src == 'true'
              with:
                node-version: 22

            - name: "Install Dependencies"
              if: steps.changes.outputs.src == 'true'
              run: |
                sudo apt-get update
                sudo apt-get install libwebkit2gtk-4.1-dev \
                  build-essential \
                  curl \
                  wget \
                  file \
                  libssl-dev \
                  libgtk-3-dev \
                  libayatana-appindicator3-dev \
                  librsvg2-dev \
                  libsoup2.4-dev

                curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh -s -- -y

                npm install --global yarn
                yarn
                yarn build

            - name: Install cargo-llvm-cov
              if: steps.changes.outputs.src == 'true'
              uses: taiki-e/install-action@cargo-llvm-cov

            - name: Generate code coverage
              if: steps.changes.outputs.src == 'true'
              working-directory: src-tauri
              run: cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info

            - name: Upload coverage to Codecov
              if: steps.changes.outputs.src == 'true'
              uses: codecov/codecov-action@v5
              with:
                files: lcov.info
                fail_ci_if_error: false
              env:
                CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
