name: "Vue Checker and Coverage"
on:
    pull_request:
    push:
        branches:
            - main

jobs:
    changes:
        name: "Changes"
        runs-on: ubuntu-latest
        outputs:
            vue: ${{ steps.changes.outputs.vue }}
        steps:
            - uses: actions/checkout@v4
            - uses: dorny/paths-filter@v3
              with:
                filters: |
                    vue:
                        - 'src/**'  
    
    lint-build:
        name: "Lint And Build"
        runs-on: ubuntu-latest
        needs: changes

        if: ${{ needs.changes.outputs.vue == 'true' || github.ref_name == 'main' }}

        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4

            - name: "Install Dependencies"
              run: |
                npm install --global yarn
                yarn

            - name: "Lint"
              run: yarn lint

            - name: "Build"
              run: yarn build
    
    test:
        name: "Test"
        runs-on: ubuntu-latest
        needs: lint-build

        if: ${{ needs.changes.outputs.vue == 'true' || github.ref_name == 'main' }}

        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4

            - name: "Install Dependencies"
              run: |
                npm install --global yarn
                yarn
                yarn build

            - name: Run vitest and report issues
              uses: roerohan/vitest-github-action@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                config: ./vitest.config.ts
                coverage: true
