name: "Vue Checker"
on:
    pull_request:
    merge_group:
    push:
        branches:
            - main

jobs:
    lint-build:
        name: "Lint And Build"
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: dorny/paths-filter@v3
              id: changes
              with:
                filters: |
                  src:
                    - 'src/**'

            - uses: actions/setup-node@v4
              if: steps.changes.outputs.src == 'true'
              with:
                node-version: 20

            - name: "Install Dependencies"
              if: steps.changes.outputs.src == 'true'
              run: |
                npm install --global yarn
                yarn

            - name: "Lint"
              if: steps.changes.outputs.src == 'true'
              run: yarn lint

            - name: "Build"
              if: steps.changes.outputs.src == 'true'
              run: yarn build
