name: "Vue Checker"
on:
    pull_request:
    merge_group:
    push:
        branches:
            - main

jobs:
    lint-build:
        name: "Lint And Build"
        runs-on: ubuntu-latest
        container:
          image: ghcr.io/brewingbytes/tauri-builder
        permissions:
          packages: read

        steps:
            - uses: actions/checkout@v4

            - name: "Install Dependencies"
              run: |
                yarn

            - name: "Lint"
              run: yarn lint

            - name: "Build"
              run: yarn build
